3scale/zync

- app/models/notification.rb
two incoming notifications are going to try create models concurrently
that will result in constraint error in the database that needs to be
recovered
> retry creating models from notifications

- app/models/notification.rb
as hitting constraint error will abort whole transaction
resulting in:
> ActiveRecord::StatementInvalid (PG::InFailedSqlTransaction: ERROR:  current transaction is aborted, commands ignored until end of transaction block
> wrap creating model in new transaction

- app/services/status_service.rb
if there are pending migrations instance will be killed
and restarted, so migrations are executed again
> check pending migrations in status api

- config/secrets.yml
`bugsnag_api_key` secret was always empty
> fix bugsnag configuration

- app/controllers/application_controller.rb
- config/secrets.yml
using ZYNC_AUTHENTICATION_TOKEN environment variable
will enable Bearer token authentication
> [api] option to enable token auth via ENV

- app/adapters/keycloak.rb
- test/adapters/keycloak_test.rb
so it always has a trailing slash
so the subsequent URI.join will keep the base path
> [keycloak] normalize endpoint

- app/models/model.rb
- app/models/update_state.rb
- app/services/incoming_notification_service.rb
- test/services/incoming_notification_service_test.rb
* foreign key requires FOR NO KEY UPDATE lock and would
not work with FOR UPDATE lock
> [model] weaker lock to not stall notification ingestion

- app/jobs/update_job.rb
- app/models/model.rb
- test/models/model_test.rb
- test/services/incoming_notification_service_test.rb
by not waiting for the lock but rather using exponential pushback
we can spread the load in the future and avoid waiting on database locks
> concurrent update jobs have exponential backoff

- .s2i/bin/run
as when updating gems there can be several versions and rails won't boot
> s2i should run bundle exec rake

- Gemfile
- Gemfile.lock
- config/application.rb
- config/initializers/prometheus.rb
- lib/prometheus/job_stats.rb
show information about how many jobs of each kind are scheduled
```
scheduled_jobs{job="UpdateJob"} 5
retried_jobs{job="UpdateJob"} 3
pending_jobs{job="UpdateJob"} 2
```
> expose job stats as prometheus metrics endpoint

- .circleci/config.yml
https://discuss.circleci.com/t/use-the-arch-cache-template-key-if-you-rely-on-cached-compiled-binary-dependencies/16129
> [circle] use arch in the cache keys

- config/initializers/prometheus.rb
- lib/prometheus/active_job_subscriber.rb
more metrics about processed jobs
those new  are runtime only, so will have to be aggregated by prometheus
the previous ones were from database, so all nodes would give same results
```
scheduled_jobs{job="UpdateJob"} 4
retried_jobs{job="UpdateJob"} 4
job_retries{adapter="Que",job_name="UpdateJob"} 6.0
failed_jobs{adapter="Que",job_name="UpdateJob"} 6.0
performed_jobs{adapter="Que",job_name="UpdateJob"} 4.0
performed_jobs{adapter="Que",job_name="ProcessEntryJob"} 4.0
enqueued_jobs{adapter="Que",job_name="UpdateJob"} 10.0
enqueued_jobs{adapter="Que",job_name="ProcessEntryJob"} 4.0
jobs_histogram_bucket{adapter="Que",job_name="UpdateJob",le="0.005"} 0.0
jobs_histogram_bucket{adapter="Que",job_name="UpdateJob",le="0.01"} 0.0
jobs_histogram_bucket{adapter="Que",job_name="UpdateJob",le="0.025"} …
```
> [prometheus] improve prometheus metrics

- config/initializers/prometheus.rb
- lib/prometheus/active_job_subscriber.rb
* all metrics should be prefixed with the project name
see https://github.com/3scale/zync/pull/78#issuecomment-346027324
> [zync] rename prometheus metrics

- Gemfile
- Gemfile.lock
fixes [THREESCALE-466](https://issues.jboss.org/browse/THREESCALE-466)
> update httpclient to support custom certificate stores [THREESCALE-466]

- app/adapters/keycloak.rb
- app/adapters/three_scale/api/instrumented_http_client.rb
- app/controllers/application_controller.rb
- app/services/integration/keycloak_service.rb
- config/secrets.yml
- test/adapters/three_scale/api/instrumented_http_client_test.rb
Mutual authentication with system.
It uses the same token that System workers to authenticate with Zync.
Zync will query system with this token in the header to identify itself
Ideas could be to use BasicAuth but we would need to modify System code base.
Can be improved later I think
> Send zync token to authenticate to System

- app/adapters/keycloak.rb
- config/application.rb
- config/keycloak.yml
- test/adapters/keycloak_test.rb
Define yaml config with extra attributes sent to keycloak. This allows anyone to pass own yaml config and configure extra payload sent to Keycloak.
closes #91
closes #89
> [keycloak] ability to configure extra client attributes

- test/test_helper.rb
Looks like at_exit hooks were evaluated at the beginning of the test suite.
Moving SimpleCov to be the first thing in the file fixes the issue.
> [test] fix reporting coverage

- lib/tasks/boot.rake
Exits with error code 1 when database is not reachable.
> [rake] boot:db task

- app/models/client.rb
- app/models/model.rb
- app/models/notification.rb
- app/services/fetch_service.rb
- app/services/integration/keycloak_service.rb
- db/migrate/20181019101631_create_clients.rb
- db/structure.sql
- test/fixtures/clients.yml
- test/fixtures/entries.yml
- test/fixtures/integrations.yml
- test/fixtures/models.yml
- test/integration/data_model_test.rb
- test/jobs/process_entry_job_test.rb
- test/services/integration/keycloak_service_test.rb
Fixes [THREESCALE-1346](https://issues.jboss.org/browse/THREESCALE-1346).
By introducing another model Client and using System API to find the last App with specific client_id we can synchronize changes even when Application is deleted and another one created with the same app_id.
> Synchronize changes with the same client_id on the same service [THREESCALE-1346]

- app/adapters/keycloak.rb
- test/adapters/keycloak_test.rb
code expected symbols, but users usually write strings in YAML
> [config] fix strings in keycloak config

- .circleci/config.yml
- Gemfile
- Gemfile.lock
validate_url does not declare dependency on it, but uses it anyway (https://github.com/perfectline/validates_url/issues/72)
zync would fail to start when development and tests dependencies are not installed
> [gemfile] fix missing public_suffix gem

- app/adapters/keycloak.rb
- app/services/integration/keycloak_service.rb
- test/adapters/keycloak_test.rb
- test/fixtures/entries.yml
- test/services/integration/keycloak_service_test.rb
Implement OAuth allowed flows for each Application based on information in https://issues.jboss.org/browse/THREESCALE-1948
Part of https://issues.jboss.org/browse/THREESCALE-774
> OAuth allowed flows per application

- Gemfile
- Gemfile.lock
validate_uri has been fixed in https://github.com/3scale/zync/pull/159
> [gemfile] no need to explicitly depend on public_suffix

- .gitignore
Ignore the `.idea` folder just like we do for Porta:
https://github.com/3scale/porta/blob/4b1e6c55d4391cee5f7b1a0b47f6202d5aaf4710/.gitignore#L20
[This file is auto generated by RubyMine for its settings](https://rider-support.jetbrains.com/hc/en-us/articles/207097529-What-is-the-idea-folder-).
> [Git ignore] .idea generated by RubyMine

- app/adapters/keycloak.rb
- config/keycloak.yml
Ability to configure timeouts of the http client used to call Keycloak.
Set default timeout in production to 3 seconds.
> Keycloak timeouts

- openshift/04-deploymentconfig-template.yml
- openshift/05-services-template.yml
This allows prometheus to scrape the metrics from a different
container and port.
> [metrics] Manage metrics in a separated container

- db/migrate/20190410112007_upgrade_que.rb
Migration can't really finish in 5 seconds.
> [db] disable statement timeout in que db migration

- openshift/04-deploymentconfig-template.yml
Imagechange trigger was missing new `que` container.
It has been added, so now `que` container points to ImageStream `zync:latest`, and ImageChange trigger pointing to `zync-latest` now manages both `zync` and `que` containers.
> Add que container to imagechange trigger

- INTEGRATE.md
JIRA: [[THREESCALE-2060] We shouldn't need to have a valid json in apicast_registry_url in the config to run porta locally](https://issues.jboss.org/browse/THREESCALE-2060)
> APICAST_REGISTRY_URL no longer required for porta to run  [THREESCALE-2060]

- app/models/model.rb
They are expected and retried exponentially.
> skip reporting lock error to bugsnag

- app/jobs/application_job.rb
plenty of jobs are retried, because they are lock errors
> [rails] do not print that job was retried

- Gemfile
- Gemfile.lock
should fix https://github.com/bugsnag/bugsnag-ruby/issues/545
> [gemfile] try bugsnag hotfix

- Gemfile
- Gemfile.lock
- app/jobs/application_job.rb
- app/jobs/process_integration_entry_job.rb
- app/jobs/update_job.rb
- test/jobs/process_integration_entry_job_test.rb
- test/jobs/update_job_test.rb
there is no need for previous jobs with the same parameters
they always take the last data from the database, so there is no reason to have more of them in flight
> [que] de-duplicate update and process integration jobs

- Gemfile
- Gemfile.lock
- app/jobs/process_entry_job.rb
- app/jobs/process_integration_entry_job.rb
- app/models/integration/kubernetes.rb
- app/models/notification.rb
- app/models/provider.rb
- app/services/discover_integration_service.rb
- app/services/fetch_service.rb
- app/services/incoming_notification_service.rb
- app/services/integration/echo_service.rb
- app/services/integration/keycloak_service.rb
- app/services/integration/kubernetes_service.rb
- app/services/integration/service_base.rb
- config/application.rb
- config/environments/development.rb
- config/environments/test.rb
- config/openshift.yml
- db/migrate/20190605094424_create_providers.rb
- db/structure.sql
- lib/tasks/que.rake
- test/fixtures/entries.yml
- test/fixtures/models.yml
- test/fixtures/providers.yml
- test/jobs/process_entry_job_test.rb
- test/models/provider_test.rb
- test/services/fetch_service_test.rb
- test/services/kubernetes_service_test.rb
Depends on https://github.com/3scale/porta/pull/844
Depends on https://github.com/3scale/3scale-operator/pull/145
> Create k8s Ingress objects [THREESCALE-2686]

- Gemfile
- Gemfile.lock
- app/adapters/abstract_adapter.rb
- test/adapters/abstract_adapter_test.rb
Very interesting error. Our test suite depends on webmock, which depends on addressable. httpclient uses addressable if available. That means URLs are parsed differently in test environment and production one.
> fix uri parse error

- app/adapters/abstract_adapter.rb
- app/adapters/rest_adapter.rb
- examples/rest-api/.gitignore
- examples/rest-api/Gemfile
- examples/rest-api/Gemfile.lock
- examples/rest-api/README.md
- examples/rest-api/app.rb
- examples/rest-api/config.ru
- examples/rest-api/openapi.yml
- test/adapters/abstract_adapter_test.rb
- test/adapters/rest_adapter_test.rb
Cleanup authentication and fix Basic/Digest auth.
Provide example Sinatra application that implements our protocol.
Also, provide OpenAPI Specification for the API and documentation of how the protocol works.
/cc @vramosp @3scale/documentation
> REST API integration example

- app/services/integration/kubernetes_service.rb
When deployed by the operator, 3scale objects have the following owner reference:
```yaml
ownerReferences:
- apiVersion: apps.3scale.net/v1alpha1
kind: APIManager
name: example-apimanager-s3
uid: 3fcf9ead-a2f3-11e9-b57e-0a543109227c
controller: true
blockOwnerDeletion: true
```
And zync won't have permissions to read that object. So just stop the recursion and use the latest valid object as a root owner reference.
/cc @miguelsorianod
> [k8s] ignore owner references that zync has no permission to

- Gemfile
- Gemfile.lock
Current version of rubyzip (1.2.3) bundled with license_finder v5.9.2 has been recently marked in [CVE-2019-16892](https://nvd.nist.gov/vuln/detail/CVE-2019-16892).
This PR bumps version of rubyzip preserving version of license_finder which we are not ready to upgrade yet. This is the same approach adopted by https://github.com/3scale/3scale_toolbox/pull/217.
Closes [THREESCALE-3732](https://issues.jboss.org/browse/THREESCALE-3732).
> Bump rubyzip version from 1.2.3 to 2.0.0

- .circleci/config.yml
- app/services/integration/kubernetes_service.rb
- test/lib/prometheus/que_stats_test.rb
- test/services/kubernetes_service_test.rb
If public route was created with `http:` scheme, do not enforce secure route edge redirect
Fixes THREESCALE-3545
The following does not prevent the merge of this PR but we should take into account that when the environment variable `KUBERNETES_ROUTE_TLS` is set to `1`, `t` or `true` then it will prevent creating 
non secure routes, which might be an issue as **Porta** has something different from **OpenShift**
This prevents removing the `:tls` option https://github.com/3scale/zync/blob/726962b98feb15f1859b0c1ad8ae72b7b6e71028/app/services/integration/kubernetes_service.rb#L6-L7
It is used in https://github.com/3scale/zync/blob/726962b98feb15f1859b0c1ad8ae72b7b6e71028/app/services/integration/kubernetes_service.rb#L263-L271
But the integration service builds all routes for both staging and …
> Route termination options follow public url scheme

- test/services/kubernetes_service_test.rb
Otherwise ROLLBACK will not be invoked
Thus transactional tests will still run inside the same global transaction
**How to reproduce:**
```shell
git checkout d8a36dfacd8ad8b2ddd56d75ec339533b953ce66
rails test  --seed 54917
```
**Fixing:**
https://app.circleci.com/pipelines/github/3scale/zync/807/workflows/a0a60d3a-1425-44bc-9335-ab3666c3194a/jobs/1426
```
1) Error:
Prometheus::QueStatsTest::WithTransaction#test_readonly_transaction:
ActiveRecord::StatementInvalid: PG::ActiveSqlTransaction: ERROR:  SET TRANSACTION ISOLATION LEVEL must be called before any query
: SET TRANSACTION ISOLATION LEVEL SERIALIZABLE READ ONLY DEFERRABLE
/home/circleci/zync/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:75:in `exec' …
```
> [random-failure] Do not forget super in after_teardown

- Dockerfile
Amazon Web Services no longer supports PostgreSQL 9.2, that reached End-of-Life in September, 2017. 
This PRs updates the PostgreSQL version by using the oficial PostgreSQL repository.
> Upgrade PostgreSQL client to 10

- .gitignore
- app/services/integration/kubernetes_service.rb
- test/services/kubernetes_service_test.rb
This is the default case of Porta account routes, which [don't accept non-TLS routes on OpenShift](https://github.com/3scale/porta/blob/933da0da4b12d1296e4960b83ca60f3f2af07f68/openshift/system/config/settings.yml#L5), yet the API returns scheme-less provider domains (`domain` and `admin_domain`).
Closes [THREESCALE-4832](https://issues.redhat.com/browse/THREESCALE-4832)
Alternative to https://github.com/3scale/zync/pull/315.
> Default Kubernetes routes to https when the scheme is missing

- openshift/02-ruby-25-ubi7-imagestream.yml
- openshift/03-buildconfig-template.yml
This PR changes the ImageStream and BuildConfig YAML templates offered as examples to build zync from source on Openshift (s2i). Instead of using centos7 as base image, it uses UBI7 Ruby 2.5 image, i.e. same one of the Dockerfile.
> Use UBI base image when building in Openshift

- .circleci/config.yml
We should be running the tests in as close an environment as possible to the one used during productization
> Switch CI image to UBI7-based ruby 2.5 image

- lib/prometheus/que_stats.rb
- test/lib/prometheus/que_stats_test.rb
- Renames the following measurement types of the `jobs_scheduled_total` Prometheus (gauge) metric:
- `<job_class>/retry` to `<job_class>/retried` (Que jobs with at least 1 retry attempt)
- `<job_class>/future` to `<job_class>/scheduled` (Que jobs scheduled to be executed in the future)
- Introduces the following new measurement types of the `jobs_scheduled_total` Prometheus (gauge) metric:
- `<job_class>/ready`: Que jobs ready to be executed for the first time (excludes: errored, expired, finished, performed)
- `<job_class>/finished`: Que jobs already performed
- `<job_class>/failed`: Que jobs that failed at least once
Related to https://github.com/3scale/infrastructure/issues/905
> New Que stats Prometheus metrics

- lib/prometheus/que_stats.rb
- test/lib/prometheus/que_stats_test.rb
Replaces raw SQL in Prometheus::QueStats#job_stats with some Arel and BabySqueel
Following https://github.com/3scale/zync/pull/334
> Refactoring Prometheus::QueStats

- lib/prometheus/que_stats.rb
- test/lib/prometheus/que_stats_test.rb
Redefines the types of Prometheus metrics on Que jobs (`que_jobs_scheduled_total`) as the following:
| Type      | Meaning                                                                                                                            |
|-----------|------------------------------------------------------------------------------------------------------------------------------------|
| ready     | Number of jobs enqueued and ready to be executed ASAP (never failed, nor got expired)                                              |
| scheduled | Number of jobs enqueued to be executed some time in the future, but not now (never failed, nor got expired)                        |
| finished  | Number of jobs that executed with success …
> Make types of Que jobs Prometheus metrics exclusive

- examples/rest-api/Gemfile.lock
This does not affect Zync itself, but will prevent dependabot from raising security issues related to the example rest-api app that is part of zync's code base.
> Bump example rest-api's rack to 2.2.3

- app/jobs/process_entry_job.rb
- config/initializers/rails_6.rb
- test/jobs/process_entry_job_test.rb
`ApplicationRecord.retry_record_not_unique` returns `nil` when it fails with `ActiveRecord::RecordNotUnique` more than once, which can happen in case of a race condition involving 3+ jobs trying to process entries that maps to the same tenant/integration type. Particularly, this makes https://github.com/3scale/zync/blob/d1d6360de9064adcf5e0e3c7b810b381edc4a87a/app/jobs/process_entry_job.rb#L27 to fail with:
```ruby
NoMethodError: undefined method `each' for nil:NilClass
```
----
Closes [THREESCALE-5632](https://issues.redhat.com/browse/THREESCALE-5632)
> Fix race condition between entry jobs trying to create same proxy integration

- Gemfile.lock
- app/jobs/process_entry_job.rb
- config/initializers/rails_6.rb
- examples/rest-api/Gemfile.lock
- test/jobs/process_entry_job_test.rb
https://github.com/3scale/zync/pull/342 [Security] Bump rack from 2.2.2 to 2.2.3
https://github.com/3scale/zync/pull/337 [Security] Bump puma from 4.3.3 to 4.3.5
https://github.com/3scale/zync/pull/347 [Security] Bump example rest-api's rack to 2.2.3
https://github.com/3scale/zync/pull/348 Fix race condition between entry jobs trying to create same proxy integration ([THREESCALE-5632](https://issues.redhat.com/browse/THREESCALE-5632))
> 3scale-2.9.0-CR1

- app/models/integration.rb
- app/models/integration/kubernetes.rb
- app/models/integration/rest.rb
- config/application.rb
- config/integrations.yml
- test/models/integration_test.rb
Disable routes creations for Kubernetes Integration by setting:
DISABLE_K8S_ROUTES_CREATION=1
> Allow disabling integrations

- app/services/integration/kubernetes_service.rb
- test/fixtures/entries.yml
- test/services/kubernetes_service_test.rb
Sometimes, after creating an OpenShift `Route` resource, Zync may get from OpenShift a response before the ingress controller acknowledges the existence of the route and therefore the `status` of the route will miss an `ingress` property. Zync relies on that property to verify if the route is active.
This PR prepares Zync for this possible response by OpenShift to the create route POST request. ~It implements up to 3 attempts to verify the status of the route, with 2 attempts after fetching again the latest state of the resource.~ It will raise an invalid status error whenever that happens and que then undertakes of retrying the job.
The PR also fixes a bug found in the verification of the conditions of the ingress based on the "type" property of each condition.
**Example of a newly …
> Fix Kubernetes resource status missing 'ingress' property

- Gemfile
- Gemfile.lock
- db/migrate/20190530080459_add_integration_state.rb
- db/structure.sql
Adding ActiveRecord::PGEnum Gem to support `enum`
**Issue**
undefined method `create_enum' error while migrating in production
> Adding activerecord-pg_enum gem

- Dockerfile
- Gemfile.lock
Updating bundler to 2.2.19 to fix cve-2020-3627
Relates to #454
Refers to https://issues.redhat.com/browse/THREESCALE-7085
> Fix CVE 2020-3627

- app/services/integration/kubernetes_service.rb
- test/services/kubernetes_service_test.rb
Kubernetes `meta/v1.OwnerReference` resources do not contain a `metadata` field and therefore Zync's `Integration::KubernetesService#owner_reference_controller` should not expect the `OpenStruct` Ruby objects that represent those resources to respond to `#metadata` and then recursively to `#[]=(value)`. Doing such will result in 
```ruby
NoMethodError: undefined method `[]=' for nil:NilClass
```
However, https://github.com/kontena/k8s-client still expects any resource reference passed as argument to `K8s::Client#get_resource` to respond to `#metadata`. To set the `metadata` field on the owner reference resource, we need to use `K8s::Resource#merge`
Closes [THREESCALE-7283](https://issues.redhat.com/browse/THREESCALE-7283)
> Fix Kubernetes service finding from owner references without metadata

- .github/workflows/fast-forward-candidate-branch.yml
Uses a PAT token like in 3scale/porta
> [gh-actions] Add workflow to create a candidate branch

- .circleci/config.yml
This will automatically install the correct version that is indicated in the Gemfile.lock file
Also fixes license_finder failing to execute
> Fix circleci installed bundler version

- config/initializers/bugsnag.rb
Allows setting a `releaseStage` in Bugsnag which is different from `RAILS_ENV`.
For example, `RAILS_ENV` can be `production`, while it can be reported to Bugsnag as `staging`.
> Add BUGSNAG_RELEASE_STAGE to Bugsnag initializer

- Gemfile.lock
The latest commit wasn't picked up and this change is required for Cachito to be able to pick up this dependency correctly. 
Big thanks to @mayorova for spotting this !! 🙌🏼
> Fix version of httpclient

- Gemfile.lock
The latest commit wasn't picked up and this change is required for Cachito to be able to pick up this dependency correctly
(cherry picked from commit f13bee99fc358c11f289b2520486194189434be1)
> Backport fix to version of httpclient

- Dockerfile
- Gemfile
- Gemfile.lock
There is an epic "Zync doesn't create routes": https://issues.redhat.com/browse/THREESCALE-7657
While this may be caused by different reasons, it seems that in some cases restarting `zync-que` pod resolves the issue (e.g. https://issues.redhat.com/browse/THREESCALE-6835)
There are some common reports on the [que-rb](https://github.com/que-rb) repo reporting similar issues - workers just stop processing the job queue, specifically https://github.com/que-rb/que/issues/241 explains that there is some kind of a deadlock that causes this.
This (and other issues that may potentially cause deadlocks) is fixed in the version [1.0.0.beta5 (2021-12-23)|https://github.com/que-rb/que/blob/master/CHANGELOG.md#100beta5-2021-12-23], or in fact 1.0.0. The currently used version is `1.0.0.beta4`.
This PR …
> Upgrade que gem to v1.1.0 to fix deadlock issues

- .circleci/config.yml
- Dockerfile
This PR does a few things:
- updates CircleCI base image, see https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034
- upgrades PostgreSQL image to 13. I don't know why there was 12 in the first place. [Supported Configurations](https://access.redhat.com/articles/2798521) doesn't specify what version of **external** PostgreSQL is supported for Zync, but it only mentions 13. The built-in database for Zync in 3scale operator is version 10, there is a JIRA to upgrade it:
[THREESCALE-8545: change support of PostgreSQL (internal db) from 10.x to 13.x](https://issues.redhat.com/browse/THREESCALE-8545)
- tweaks the Dockerfile to fix the failing build (see inline comments)
> Fix CircleCI builds

- test/controllers/tenants_controller_test.rb
This was spotted by @jlledom here: https://github.com/3scale/zync/pull/502#discussion_r1244769959
The test is not correct, as by default (without `as: :json`) the request is sent with `application/x-www-form-urlencoded` Content-Type, and parameters wrapping is only enabled for JSON.
Also, I think we only support JSON (we probably need to reject requests with other content-types). So, the test should be for JSON also.
> Fix tenants controller test params wrapping

- .circleci/config.yml
- Dockerfile
- db/structure-10.sql
- db/structure.sql
- lib/tasks/db.rake
Add PostgreSQL 12 to tests, as we're still using it.
This PR also changes the names of the `structure.sql` file.
There have been two versions: `structure.sql` that was used for PostgreSQL version 10 and below, and `structure-12.sql` used for all other versions. This is very confusing as:
1. `structure-12.sql` would be used for PostgreSQL v13
2. `structure-12.sql` would also be used for PostgreSQL v11, BUT it would not work because of one statement unsupported in v11. There was in fact some discussion around it in Slack, but as we lost history, I don't think I'll be able to recover the details.
The differences between the two files are:
1. The following statement:
```
SET default_table_access_method = heap;
```
This appeared in PostgreSQL v12, and is not supported in earlier versions (this …
> Add PostgreSQL 12 to tests and prevent from using unsupported versions

- .circleci/config.yml
- Gemfile
- Gemfile.lock
- db/migrate/20230629131935_update_que_tables_to_version5.rb
- db/structure-10.sql
- db/structure.sql
Based on https://github.com/3scale/zync/pull/502
Gradual upgrade, based on the instructions here: https://github.com/que-rb/que/blob/master/CHANGELOG.md#200beta1-2022-03-24
>Recommended upgrade process:
>When using Que 2.x, a job enqueued with Ruby 2.7 will run as expected on Ruby 3. We recommend:
>Upgrade your project to the latest 1.x version of Que (1.3.1+)
IMPORTANT: adds support for zero downtime upgrade to Que 2.x, see changelog below
>Upgrade your project to Ruby 2.7 and Rails 6.x if it is not already
>Upgrade your project to Que 2.x but stay on Ruby 2.7
>IMPORTANT: You will need to continue to run Que 1.x workers until all jobs enqueued using Que 1.x (i.e. with a job_schema_version of 1) have been finished. See below
>Upgrade your project to Ruby 3
This is the first part, …
> Upgrade Que to version 1.4 (prep for v2)

- Gemfile.lock
needed because of some issues in production builds with previous version
> use newer bundler for prod image issues

- .circleci/config.yml
- CONTRIBUTING.md
- Dockerfile
- Gemfile
- Gemfile.lock
- INSTALL.md
- app/adapters/three_scale/api/instrumented_http_client.rb
- app/services/integration/kubernetes_service.rb
- test/jobs/process_entry_job_test.rb
- test/services/incoming_notification_service_test.rb
Some issues encountered in the upgrade:
1. The dependency `k8s-ruby`, or rather its dependency `recursive-open-struct` uses deprecated arguments passing here: https://github.com/aetherknight/recursive-open-struct/blob/main/lib/recursive_open_struct.rb#L188
It seems that it kind of supports Ruby 3 https://github.com/aetherknight/recursive-open-struct/blob/main/.travis.yml#L15
As well as `k8s-ruby` claims that it supports Ruby 3.1 https://github.com/k8s-ruby/k8s-ruby/commit/30d4db1b8ad991660098c89e55b35ee18aa216c9
But probably it's an edge case...
With Ruby 2.7 there is a deprecation warning: 
```
/home/dmayorov/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/recursive-open-struct-1.1.3/lib/recursive_open_struct.rb:188: warning: Using the last argument as keyword parameters is …
```
> Ruby upgrade to v3

- Gemfile
- Gemfile.lock
- Rakefile
- doc/licenses/licenses.xml
We are not using capistrano for deployments, so just cleaning up unneeded deps.
Also, when updating the licenses file I realized that it was not updated after Rails upgrade.
Probably we need to generate it in the container build, like we do for Porta...
> :broom: Remove bugsnag-capistrano dependency and update licenses

- Gemfile.lock
The default version of `json` gem for Ruby 3.1 is `2.6.1`, see: https://stdgems.org/3.1.0/
So, set it in the `Gemfile.lock` to avoid the error:
```
You have already activated json 2.6.1, but your Gemfile requires json 2.5.1. Since json is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports json as a default gem. (Gem::LoadError)
```
> Upgrade JSON default gem

- app/adapters/abstract_adapter.rb
- test/adapters/abstract_adapter_test.rb
Fixing the issue: https://issues.redhat.com/browse/THREESCALE-11063
It was failing previously with:
```
AbstractAdapter::OIDC::AuthenticationError: Unknown Content-Type
```
> THREESCALE-11063: Fix parsing response if Content-Type contains charset

- .circleci/config.yml
**What this PR does / why we need it**:
Postgres 13 will be EOL soon, we need to officially support Postgres14.
After a research, I would say we already support it completely, so this PR only updates the CircleCI pipeline. More info below.
**Which issue(s) this PR fixes** 
https://issues.redhat.com/browse/THREESCALE-8920
**Special notes for your reviewer**:
This is the list of checks and tests I made:
- Check our `pg` gem version supports Postgres 14
- We use `1.2.3`
- The first mention to Postgres 14 in the Changelog is in the version [`1.3.0`](https://github.com/ged/ruby-pg/blob/master/History.md#v130-2022-01-20-michael-granger-gedfaeriemudorg), however, everything seems to work fine for us using `1.2.3`.
- Reset database with `bundle exec rails db:reset`
- Working fine locally
- Create …
> THREESCALE-8920: Support for PostgreSQL 14

- config/database.yml
Our current `pg` gem already supports TLS protected connections to Postgres, however we need to add a few env. vars for the user to provide the certificates and keys.
https://issues.redhat.com/browse/THREESCALE-4185
These variables will be set by the operator. Check the ticket: https://issues.redhat.com/browse/THREESCALE-11156
> THREESCALE-4185: Support TLS protected PostgreSQL

- app/services/fetch_service.rb
- test/fixtures/integrations.yml
- test/fixtures/models.yml
- test/fixtures/services.yml
- test/integration/data_model_test.rb
- test/services/fetch_service_test.rb
Fixes https://issues.redhat.com/browse/THREESCALE-8271
It adds `service_id` parameter when fetching application from porta.
> THREESCALE-8271: Add service_id param when fetching client by client ID

- .circleci/config.yml
Use a `cimg` image for postgres 10, because `circleci` is deprecated.
> Switch to a newer postgres 10 image

- Gemfile.lock
This is the one we use in the base for the current productized images `registry.redhat.io/ubi9/ruby-31:1`
> Change bundler version to 2.3.27 to match the system bundler

- .circleci/config.yml
- Dockerfile
`registry.access.redhat.com/ubi9/ruby-31` is deprecated...
> Using plain ubi9 base image

- db/migrate/20251008141931_replace_md5_with_hashtext_in_que_job_notify.rb
- db/structure-10.sql
- db/structure.sql
This is a temporary patch until upstream fix is merged, see https://github.com/que-rb/que/pull/437
backport from #565
> avoid MD5 for FIPS support
