3scale/zync

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/notifications_controller.rb, app/jobs/update_job.rb, app/services/fetch_service.rb, config/application.rb, config/routes.rb, lib/application_responder.rb, test/controllers/notifications_controller_test.rb
=> Notifications API

.circleci/config.yml, Gemfile, Gemfile.lock, app/jobs/process_integration_entry_job.rb, test/controllers/notifications_controller_test.rb, test/integration/data_model_test.rb, test/test_helper.rb
* alpine postgres
* fix job deserialization
* add debugging tools
=> parallelized build

app/controllers/tenants_controller.rb, app/models/tenant.rb, config/routes.rb, lib/application_responder.rb, test/controllers/tenants_controller_test.rb
idempotent endpoint that is locking the record
=> api to create & update tenants

app/models/update_state.rb
acquire a lock so updates are serialized
=> prevent data races when updating

app/controllers/statuses_controller.rb, app/services/status_service.rb, config/routes.rb, test/controllers/statuses_controller_test.rb, test/services/status_service_test.rb
something for OpenShift healthchecks
=> status api

.s2i/environment
to print all requests and resonses to 3scale API
=> enable verbose logging

config/environments/production.rb
debug log in production can be too much
=> ability to control log level in production

.s2i/environment, app/models/application_record.rb, app/models/notification.rb, app/models/tenant.rb
* revert verbose logging
* log unique constraint exceptions
=> better logging

app/services/fetch_service.rb
info should be the normal production log level
=> reduce log level of the fetch service

Gemfile, Gemfile.lock, config/initializers/bugsnag.rb, config/secrets.yml
to track errors in production environment
=> integrate bugsnag

.circleci/config.yml, .gitignore, Gemfile, Gemfile.lock, codecov.yml, test/test_helper.rb
to have code coverage in the PR
=> integrate codecov

.circleci/config.yml, Gemfile, Gemfile.lock, doc/dependency_decisions.yml
to ensure we use only free open source software
=> integrate license finder

app/models/application.rb, config/application.rb, config/database.yml
* less crashes - faster
* more worker threads
=> tune que workres

Gemfile, Gemfile.lock, config/skylight.yml, doc/dependency_decisions.yml
for easier tracking of performance issues
=> integrate skylight

app/models/notification.rb, app/models/tenant.rb
* faster retries
* less locking
=> speedup tenant and notification endpoints

app/controllers/notifications_controller.rb
instead of bubbling the exception
=> handle invalid notifications

app/adapters/keycloak.rb, app/services/integration/keycloak_service.rb
* enabled only when live
* push also name and description
=> persist application state to keycloak

app/controllers/status/live_controller.rb, app/controllers/status/ready_controller.rb
=> [api] skip authentication in status controllers

Gemfile, Gemfile.lock, config/skylight.yml, doc/dependency_decisions.yml
=> remove skylight

Gemfile, Gemfile.lock, app/adapters/keycloak.rb, app/jobs/process_entry_job.rb, app/jobs/process_integration_entry_job.rb, app/models/entry.rb, app/models/integration.rb, app/models/integration/keycloak.rb, app/services/discover_integration_service.rb, app/services/integration/keycloak_service.rb, config/application.rb, config/initializers/message_bus.rb, config/initializers/que.rb, config/puma.rb, config/spring.rb, test/jobs/process_entry_job_test.rb, test/jobs/process_integration_entry_job_test.rb, test/services/discover_integration_service_test.rb
so other components can consume status of zync
=> integrate message_bus

config/initializers/message_bus.rb, config/puma.rb, config/spring.rb
so tasks like dropping db work
=> [message_bus] don't start message bus in rake

config/initializers/message_bus.rb
MessageBus would crash when started by Spring.
=> [message_bus] don't run message bus in spring

config/environments/production.rb
so it can be easily consumed by ElasticSearch
=> [rails] json logging in production

LICENSE
https://issues.jboss.org/browse/THREESCALE-285
=> Using Apache 2.0 License

app/adapters/keycloak.rb, test/adapters/keycloak_test.rb
like endpoint it tried to connect to
related to https://github.com/3scale/zync/issues/59<D-3>
=> more information in timeout errors

app/jobs/process_entry_job.rb, test/jobs/process_entry_job_test.rb
fixes https://github.com/3scale/zync/issues/63
=> don't create integration for deleted proxy

.s2i/bin/run, config/initializers/bugsnag.rb, db/structure.sql
as this happens on every deploy it just creates noise
=> don't report db creation errors to bugsnag

Gemfile.lock, config/application.rb, config/environments/production.rb, config/initializers/filter_parameter_logging.rb, lib/lograge/custom_options.rb
improve logging by adding controller parameters
=> log controller params in lograge

app/adapters/three_scale/api/instrumented_http_client.rb, app/services/fetch_service.rb, config/initializers/lograge.rb, lib/lograge/custom_options.rb, lib/lograge/http_subscriber.rb
* use rails instrumentation
* add lograge logging
=> instrument threescale http client

app/adapters/three_scale/api/instrumented_http_client.rb
* track request/response ids
* track params
=> improve http request instrumentation

CONTRIBUTING.md
Part of https://issues.jboss.org/browse/THREESCALE-285
Simple contributing.md
=> [Documentation] Adding a CONTRIBUTING.md file

lib/prometheus/job_stats.rb
* disable statement timeout for current transaction
* mark transaction as read only and deferrable to prevent locking
This avoids timing out when there is ~1M jobs in the queue.
=> [prometheus] don't timeout when there is too many jobs

lib/prometheus/job_stats.rb
=> [prometgeus] job stats are actually a gauge type

.circleci/config.yml
to get rid of 404s due to old apt cache
=> [circle] update before running apt install

app/adapters/three_scale/api/instrumented_http_client.rb
=> fix a typo, ednpoint -> endpoint

app/adapters/keycloak.rb, lib/lograge/subscriber_base.rb, test/adapters/keycloak_test.rb
* send response information to bugsnag
* log the response on errors
=> improve capturing failed keycloak requests

.s2i/bin/run, Gemfile, Gemfile.lock, Rakefile, config/initializers/bugsnag.rb
* and don't crash when BUGSNAG_API_KEY is missing
=> [gemfile] update bugsnag

app/adapters/three_scale/api/instrumented_http_client.rb
If there is a way to reach System internally via Service it should be preferred.
=> [fetch] detect when running on openshift and use services instead of routes

Gemfile.lock
* the git sha no longer exists
* https://github.com/nahi/httpclient/pull/386
=> [bundle] update httpclient

test/adapters/keycloak_test.rb, test/integration/data_model_test.rb, test/test_helper.rb
This full integration test will act as a base for reproduction test of [THREESCALE-1346](https://issues.jboss.org/browse/THREESCALE-1346).
=> [test] full integration test to create/update/delete a client

config/database.yml, lib/tasks/boot.rake
So it is obvious the task completed successfully.
=> [rake] print information about connected database

openshift/00-secrets-template.yml, openshift/01-zync-imagestream.yml, openshift/02-ruby-24-centos7-imagestream.yml, openshift/03-buildconfig-template.yml, openshift/04-deploymentconfig-template.yml, openshift/05-services-template.yml, openshift/06-route-template.yml, openshift/Makefile
Added zync openshift manifests. 
It has been also added a Makefile to simplify the openshift application creation.
=> Add zync openshift manifests

.circleci/config.yml
Closes [THREESCALE-2004](https://issues.jboss.org/browse/THREESCALE-2004)
/cc @guicassolato
=> [circleci] test against postgresql 10

Brewfile, INSTALL.md, INTEGRATE.md, README.md
Documentation to locally install Zync and to integrate it with Porta/System and keycloak.
Fixes [THREESCALE-2068](https://issues.jboss.org/browse/THREESCALE-2068)
=> [Doc] Installation guide & Integration guide

app/models/entry.rb, app/services/integration/keycloak_service.rb, test/integration/data_model_test.rb
Fixes [THREESCALE-1791](https://issues.jboss.org/browse/THREESCALE-1791)
=> THREESCALE-1791 - 404 Application cannot be deleted on Keycloak

Gemfile.lock
=> [gemfile] rollback  #169 and  #171

Gemfile, Gemfile.lock, config.ru, config/application.rb, config/initializers/prometheus.rb, config/initializers/que.rb, config/puma.rb, config/que.yml, db/migrate/20190410112007_upgrade_que.rb, db/structure.sql, lib/prometheus/job_stats.rb, lib/prometheus/worker_stats.rb, lib/tasks/simulate.rake, openshift/04-deploymentconfig-template.yml, openshift/05-services-template.yml
* Upgrade que to 1.0.0beta3 (using pubsub in pg)
* Listen on a second port (9393) and respond with prometheus metrics
* Do not queue requests into puma
=> Que upgrade

config/initializers/que.rb
=> [que] do not log internals

openshift/04-deploymentconfig-template.yml
Fixing the temaplate command startup
=> Fixing the command for start que

INTEGRATE.md
Changes:
1. The queue was changed from `low` to `zync` in a previous PR, but this one also changes it in the explanation.
2. Change the spaces to make it more readable 😄
=> [Doc] [Integrate] Fix spaces and mention the right queue

.dockerignore, .gitignore, Dockerfile, openshift/03-buildconfig-template.yml
=> [oc] added buildconfig for ruby-24 with bundler 2

Gemfile, Gemfile.lock
Do not depend on a topic branch in git.
=> [gemfile] use latest bugsnag

app/services/integration/kubernetes_service.rb, test/services/kubernetes_service_test.rb
OpenShift is not admitting routes when they are recreated frequently. It is better to update the existing ones.
=> [k8s] fix accidentally deleting just created routes

test/services/incoming_notification_service_test.rb
do not use Thread#kill as it would leave broken connection, that can't be used later
=> fix deadlocking tests

app/services/integration/kubernetes_service.rb, test/adapters/rest_adapter_test.rb
Do not patch Route object in k8s, but rather recreate it.
=> k8s Route object fixes

.circleci/config.yml, Dockerfile, docker-compose.yml, test/lib/prometheus/que_stats_test.rb
THREESCALE-3367
Support UBI7 (Universal Base Image) image for Zync
=> Use UBI7 Ruby image

Gemfile.lock
As the current version is yanked
=> [gem] Update codecov

.circleci/config.yml, Dockerfile, openshift/02-ruby-25-ubi7-imagestream.yml
=> Bump ruby build image to v2.7

Dockerfile, Gemfile.lock
Refers to https://issues.redhat.com/browse/THREESCALE-7085
=> Fix CVE 2020-3627

.circleci/config.yml, Dockerfile, Makefile, db/structure-12.sql, lib/tasks/db.rake
Transitioning to 12 as the stable version
The community image is now built on top of UBI8
=> Support Postgresql 10 and 12

app/jobs/application_job.rb
Zync `UpdateJob` retries on `Errno::ECONNREFUSED` and `Model::LockTimeoutError` exceptions have been broken since we upgraded to Rails 6 (#440).
This is the case, e.g., when `UpdateState` fails to acquire a lock for a model and raises a `Model::LockErrorTiemout` at https://github.com/3scale/zync/blob/38d145ead0053799eb5f2c4fdb169ac57394d1b6/app/models/model.rb#L38
Our custom implementation for `ActiveJob::Base.retry_on` (to add debug log level) did not comply with the new Rails 6 API for the `ActiveJob::Base.retry_job` method, causing an `ArgumentError` raised when failed jobs were attempted to be enqueued for retry, e.g.:
```
E, [2021-07-27T07:08:32.919387 #1] ERROR -- : {"lib":"que","hostname":"zync-que-1-fkmkx","pid":1,"thread":18925860,"event":"job_errored","job_id":3,"elapsed":0.38509 …
```
=> Fix custom ActiveJob::Base.rescue_from after upgrading to Rails 6

.s2i/bin/run
A follow-up for https://github.com/3scale/zync/pull/514
=> Remove bugnsag-capistrano rake command
